jobs:
- sparkJob:
    args:
    - gs://input-bucket
    - gs://output-location
    jarFileUris:
    - gs://rislabs/sparky/sparky-1.0.jar
    mainClass: com.sparky.examples.Sparky1
  stepId: job-21ed56c7
placement:
  managedCluster:
    clusterName: cluster-73ac
    config:
      gceClusterConfig:
        networkUri: default
        zoneUri: us-central1-b
      masterConfig:
        diskConfig:
          bootDiskSizeGb: 500
          bootDiskType: pd-standard
        machineTypeUri: n1-standard-4
        numInstances: 1
      softwareConfig:
        imageVersion: 2.0-debian10
      workerConfig:
        diskConfig:
          bootDiskSizeGb: 500
          bootDiskType: pd-standard
        machineTypeUri: n1-standard-4
        numInstances: 2
parameters:
  - name: INPUT_BUCKET_URI
    description: wordcount input bucket URI
    fields:
      - jobs['job-21ed56c7'].sparkJob.args[0]
  - name: OUTPUT_FOLDER_URI
    description: wordcount output folder URI
    fields:
      - jobs['job-21ed56c7'].sparkJob.args[1]